-- =====================================================================
--  TREND EVENTS — MySQL database
--  Generated by database/build-sql.mjs from the website data (src/data.js,
--  src/servicePages.js) — texts and image paths match the frontend exactly.
--  MySQL 5.7+ / MariaDB 10.3+ · InnoDB · utf8mb4_unicode_ci · phpMyAdmin ready
--
--  Image columns hold either a site path ("/images/...") or a full URL.
-- =====================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS password_resets, event_build_services, event_builds, quote_requests, saved_venues, users,
  portfolio_images, portfolio_items, package_items, packages, venue_images, venue_category_map,
  venues, venue_categories, service_images, service_features, services, service_categories,
  event_type_features, event_types, guest_ranges, cities, site_settings;

-- 1. CITIES
CREATE TABLE cities (
  id         INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name       VARCHAR(100) NOT NULL,
  slug       VARCHAR(120) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active  TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uq_cities_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO cities (id, name, slug, sort_order) VALUES
(1, 'London', 'london', 1),
(2, 'Birmingham', 'birmingham', 2),
(3, 'Manchester', 'manchester', 3),
(4, 'Liverpool', 'liverpool', 4),
(5, 'Edinburgh', 'edinburgh', 5);

-- 2. GUEST RANGES ("Number of guests" dropdown; max NULL = no limit)
CREATE TABLE guest_ranges (
  id         INT UNSIGNED NOT NULL AUTO_INCREMENT,
  label      VARCHAR(50) NOT NULL,
  min_guests INT NOT NULL DEFAULT 0,
  max_guests INT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uq_guest_ranges_label (label)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO guest_ranges (id, label, min_guests, max_guests, sort_order) VALUES
(1, 'Up to 50 guests', 0, 50, 1),
(2, '50–100 guests', 50, 100, 2),
(3, '100–200 guests', 100, 200, 3),
(4, '200–400 guests', 200, 400, 4),
(5, '400+ guests', 400, NULL, 5);

-- 3. EVENT TYPES — name is plural (sections, Our Work filter), form_label is singular (dropdowns)
CREATE TABLE event_types (
  id            INT UNSIGNED NOT NULL AUTO_INCREMENT,
  slug          VARCHAR(120) NOT NULL,
  name          VARCHAR(150) NOT NULL,
  form_label    VARCHAR(150) NOT NULL,
  tagline       VARCHAR(255) NULL,
  description   TEXT NULL,
  min_guests    INT NULL,
  max_guests    INT NULL,
  image         VARCHAR(255) NULL,
  show_in_forms TINYINT(1) NOT NULL DEFAULT 1,
  sort_order    INT NOT NULL DEFAULT 0,
  is_active     TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uq_event_types_slug (slug),
  KEY idx_event_types_forms (show_in_forms, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE event_type_features (
  id            INT UNSIGNED NOT NULL AUTO_INCREMENT,
  event_type_id INT UNSIGNED NOT NULL,
  feature       VARCHAR(255) NOT NULL,
  sort_order    INT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_etf_event_type (event_type_id, sort_order),
  CONSTRAINT fk_etf_event_type FOREIGN KEY (event_type_id) REFERENCES event_types (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO event_types (id, slug, name, form_label, tagline, description, min_guests, max_guests, image, show_in_forms, sort_order) VALUES
(1, 'weddings', 'Weddings', 'Wedding', 'From intimate ceremonies to grand receptions, designed around your love story.', 'Your wedding day deserves a team that sweats every detail so you never have to. From the first venue visit to the last dance, we design a celebration that feels unmistakably yours — elegant florals, candlelit tablescapes, flawless timing and a guest experience people talk about for years.', 50, 500, '/images/event-wedding.jpg', 1, 1),
(2, 'birthdays', 'Birthdays', 'Birthday', 'Milestone birthdays and surprise parties styled to perfection.', 'Whether it is a first birthday, a sweet sixteen or a glamorous 50th, we turn your milestone into a party to remember. Choose a theme, a colour palette and a vibe — we bring it to life with styling, balloons, cakes and entertainment.', 20, 250, '/images/event-birthday.jpg', 1, 2),
(3, 'engagements', 'Engagements', 'Engagement', 'Proposals and engagement parties worth remembering forever.', 'From a secret proposal to an engagement party for all your loved ones, we create romantic moments with soft lighting, white florals and beautiful details. We handle the logistics quietly, so the only thing you need to focus on is the question — and the celebration afterwards.', 2, 200, '/images/engagment-1.avif', 1, 3),
(4, 'baby-showers', 'Baby Showers', 'Baby Shower', 'Soft, beautiful celebrations to welcome the newest arrival.', 'Celebrate the newest arrival with a soft, beautifully styled baby shower or gender reveal. We design pastel palettes, dreamy balloon arches and sweet treats, so the parents-to-be can simply relax and enjoy the day with family and friends.', 15, 100, '/images/event-baby-shower.jpg', 1, 4),
(5, 'private-parties', 'Private Parties', 'Private Party', 'Anniversaries, dinners and soirées hosted with effortless style.', 'Anniversaries, family dinners, cocktail evenings or just because — our private parties are hosted with effortless style. We find the right space, curate the menu and set the mood, so you can be a guest at your own party.', 10, 300, '/images/private-parties.avif', 1, 5),
(6, 'corporate-events', 'Corporate Events', 'Corporate Event', 'Company celebrations, team events and client evenings.', 'Team celebrations, client evenings, summer parties and company milestones — delivered on time, on budget and on brand. We work with your team to create events that strengthen relationships and reflect the quality of your business.', 30, 1000, 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1600&q=75', 1, 6),
(7, 'conferences', 'Conferences', 'Conference', 'Seamless conferences with full technical production.', 'We plan conferences that run seamlessly from registration to the closing keynote. Our production team takes care of the stage, screens and sound, while our planners manage speakers, schedules and guests.', 50, 2000, '/images/conference.avif', 1, 7),
(8, 'product-launches', 'Product Launches', 'Product Launch', 'Launches that make an entrance and get people talking.', 'Make an entrance. We create launch events with dramatic reveals, immersive design and content-ready moments that get your product seen and shared — by press, partners and customers alike.', 50, 800, '/images/event-product-launch.jpg', 1, 8),
(9, 'award-nights', 'Award Nights', 'Award Night', 'Red-carpet evenings with staging, lighting and entertainment.', 'Red carpets, glittering stages and perfectly timed ceremonies. We produce award nights that honour achievement in style — from the welcome drinks to the final standing ovation.', 100, 1000, '/images/event-award-night.jpg', 0, 9),
(10, 'christmas-parties', 'Christmas Parties', 'Christmas Party', 'Festive parties for teams, families and friends.', 'Festive parties that bring teams, friends and families together. From elegant winter dinners to full-on themed parties, we take care of the décor, food, music and fun, so everyone can celebrate the season.', 20, 1000, '/images/event-christmas-party.jpg', 1, 10),
(11, 'brand-events', 'Brand Events', 'Brand Event', 'Immersive brand experiences that bring your story to life.', 'Pop-ups, activations and immersive brand experiences that bring your story to life. We combine creative design with smart production to create spaces people want to step into, photograph and remember.', NULL, NULL, '/images/event-brand-event.jpg', 0, 11),
(12, 'other', 'Other Event', 'Other Event', NULL, NULL, NULL, NULL, NULL, 1, 12);

INSERT INTO event_type_features (event_type_id, feature, sort_order) VALUES
(1, 'Venue sourcing & site visits', 1),
(1, 'Concept, styling & floral design', 2),
(1, 'Catering, cake & bar', 3),
(1, 'Photography, videography & entertainment', 4),
(1, 'Full planning & on-the-day coordination', 5),
(2, 'Themed décor & balloon installations', 1),
(2, 'Custom cakes & dessert tables', 2),
(2, 'DJ, live music or entertainers', 3),
(2, 'Venue, catering & drinks', 4),
(2, 'Photography & photo booths', 5),
(3, 'Surprise proposal planning', 1),
(3, 'Sweetheart tables & floral backdrops', 2),
(3, 'Candlelight & ambient lighting', 3),
(3, 'Private dining or party venues', 4),
(3, 'Photographer to capture the moment', 5),
(4, 'Pastel styling & balloon arches', 1),
(4, 'Gender reveal moments', 2),
(4, 'Cakes, cupcakes & dessert tables', 3),
(4, 'Games, favours & décor', 4),
(4, 'Venue or at-home setup', 5),
(5, 'Private venues & dining rooms', 1),
(5, 'Curated menus & cocktail bars', 2),
(5, 'Table styling & florals', 3),
(5, 'Music & entertainment', 4),
(5, 'Hosting & guest management', 5),
(6, 'Venue sourcing & negotiation', 1),
(6, 'Branding & event design', 2),
(6, 'Catering & drinks packages', 3),
(6, 'AV, staging & lighting', 4),
(6, 'Guest registration & management', 5),
(7, 'Auditoriums & breakout rooms', 1),
(7, 'Full technical production & LED screens', 2),
(7, 'Speaker & agenda management', 3),
(7, 'Registration, badges & signage', 4),
(7, 'Catering & networking breaks', 5),
(8, 'Creative concept & reveal moments', 1),
(8, 'Staging, lighting & special effects', 2),
(8, 'Press & influencer management', 3),
(8, 'Brand activations', 4),
(8, 'Photo & video content', 5),
(9, 'Red carpet & welcome experience', 1),
(9, 'Stage design, lighting & screens', 2),
(9, 'Show running & hosts', 3),
(9, 'Gala dinner & drinks', 4),
(9, 'Live entertainment', 5),
(10, 'Festive themes & winter styling', 1),
(10, 'Christmas dinner menus', 2),
(10, 'DJs, bands & entertainment', 3),
(10, 'Exclusive or shared party venues', 4),
(10, 'Photo booths & favours', 5),
(11, 'Experiential concepts', 1),
(11, 'Set build & bespoke installations', 2),
(11, 'Lighting, sound & LED', 3),
(11, 'Staffing & hosts', 4),
(11, 'Social content capture', 5);

-- 4. SERVICE CATEGORIES
CREATE TABLE service_categories (
  id         INT UNSIGNED NOT NULL AUTO_INCREMENT,
  slug       VARCHAR(120) NOT NULL,
  name       VARCHAR(150) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uq_service_categories_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO service_categories (id, slug, name, sort_order) VALUES
(1, 'planning-design', 'Planning & Design', 1),
(2, 'food-decor', 'Food & Décor', 2),
(3, 'photo-entertainment', 'Photo & Entertainment', 3),
(4, 'event-production', 'Event Production', 4);

-- 5. SERVICES — slug = URL /services/<slug>; is_featured = the 10 Home cards (sort_order 1–10)
CREATE TABLE services (
  id                INT UNSIGNED NOT NULL AUTO_INCREMENT,
  category_id       INT UNSIGNED NOT NULL,
  slug              VARCHAR(120) NOT NULL,
  name              VARCHAR(150) NOT NULL,
  short_description VARCHAR(255) NULL,
  tagline           VARCHAR(255) NULL,
  long_description  TEXT NULL,
  image             VARCHAR(255) NULL,
  is_featured       TINYINT(1) NOT NULL DEFAULT 0,
  sort_order        INT NOT NULL DEFAULT 0,
  is_active         TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uq_services_slug (slug),
  KEY idx_services_category (category_id),
  KEY idx_services_featured (is_featured, sort_order),
  CONSTRAINT fk_services_category FOREIGN KEY (category_id) REFERENCES service_categories (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE service_features (
  id         INT UNSIGNED NOT NULL AUTO_INCREMENT,
  service_id INT UNSIGNED NOT NULL,
  feature    VARCHAR(255) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_sf_service (service_id, sort_order),
  CONSTRAINT fk_sf_service FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE service_images (
  id         INT UNSIGNED NOT NULL AUTO_INCREMENT,
  service_id INT UNSIGNED NOT NULL,
  image_path VARCHAR(255) NOT NULL,
  alt_text   VARCHAR(255) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_si_service (service_id, sort_order),
  CONSTRAINT fk_si_service FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO services (id, category_id, slug, name, short_description, tagline, long_description, image, is_featured, sort_order) VALUES
(1, 1, 'event-planning', 'Full Event Planning', 'Full planning, coordination & concept design', 'From the first idea to the final goodbye.', 'Planning an event means hundreds of decisions, dozens of suppliers and a timeline that has to run to the minute. Our planners take all of that off your shoulders. We start by understanding your vision, your guests and your budget, then build a clear plan and a creative concept around it.

From venue visits and supplier contracts to seating plans and the running order on the day, one dedicated planner stays with you from start to finish — so you always know who to call.', '/images/services/event-planning.jpg', 1, 1),
(2, 1, 'event-coordination', 'Event Coordination', 'On-the-day management so you can relax', 'Relax — we run the day.', 'You have planned every detail; now you deserve to enjoy it. Our coordinators take over in the final weeks, confirm every supplier, build the running order and manage the event on the day — from the first delivery to the last guest leaving.

While you celebrate, we handle timings, suppliers, guests and any surprises quietly behind the scenes.', '/images/about-team.jpg', 0, 101),
(3, 1, 'event-concept-and-design', 'Event Concept & Design', 'A creative vision built around you', 'A creative vision built around you.', 'Every memorable event starts with a strong idea. Our designers turn your style, story and inspiration into a complete creative concept — colour palette, materials, florals, lighting and layout — presented in mood boards and 3D visuals.

Once you love the concept, we bring it to life with our décor, floral and production teams.', '/images/services/concept.jpg', 0, 102),
(4, 1, 'venue-finding', 'Venue Finding', 'The perfect space, sourced for you', 'The perfect space, sourced for you.', 'The venue sets the tone for everything else. Tell us your date, guest numbers, style and budget, and we will shortlist the best spaces — from grand ballrooms and rooftops to gardens, restaurants and unique hidden gems.

We arrange the viewings, negotiate the terms and check every technical detail, so you book with confidence.', 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1600&q=75', 0, 103),
(5, 1, 'event-styling', 'Event Styling', 'Every detail styled to your taste', 'Every detail styled to your taste.', 'Styling is where your event gets its personality. We choose and place every element — furniture, linens, tableware, candles, signage and décor accents — so the whole space feels cohesive, intentional and beautiful.

From lounge areas and welcome points to photo corners, every angle is styled to look perfect in person and in photographs.', '/images/services/styling.jpg', 0, 104),
(6, 2, 'catering', 'Catering', 'Exquisite menus for every occasion', 'Exquisite menus for every occasion.', 'Great food turns an event into an experience. Our chefs design menus around your taste, your guests and your theme — from elegant plated dinners and sharing feasts to canapés, food stations and late-night bites.

We take care of tastings, dietary requirements, service staff and the bar, so every course arrives on time and looks as good as it tastes.', '/images/services/catering.jpg', 1, 3),
(7, 2, 'decoration', 'Decoration', 'Bespoke styling & floral designs', 'Spaces transformed, down to the smallest detail.', 'Décor is what guests remember first. Our design team creates bespoke concepts — from romantic white florals and candlelight to bold, modern themes — and brings them to life with floral installations, backdrops, table styling and lighting.

Every piece is designed for your venue and your story. We handle the full build and the take-down, so the room looks perfect when the doors open.', '/images/event-engagement.jpg', 1, 2),
(8, 2, 'flowers', 'Flowers', 'Florals arranged by expert designers', 'Florals arranged by expert designers.', 'Flowers bring life, colour and fragrance to every celebration. Our florists design everything from bridal bouquets and buttonholes to tall centrepieces, floral arches and ceiling installations — using fresh, seasonal blooms.

We source the flowers, build the arrangements on site and make sure they look perfect from the first photo to the last dance.', '/images/services/flowers.jpg', 0, 107),
(9, 2, 'cakes-and-desserts', 'Cakes & Desserts', 'Showstopping cakes and dessert tables', 'Showstopping cakes and dessert tables.', 'A beautiful cake is often the centrepiece of the celebration. Our pastry partners create custom cakes in any style — classic tiered wedding cakes, modern sculpted designs and birthday showstoppers — that taste as good as they look.

Complete the experience with a styled dessert table full of macarons, mini desserts and sweet treats for your guests.', '/images/services/cakes.jpg', 0, 108),
(10, 2, 'table-styling', 'Table Styling', 'Tablescapes that set the mood', 'Tablescapes that set the mood.', 'Your guests spend most of the event at the table, so every detail matters. We design tablescapes with the perfect linens, chargers, cutlery, glassware, candles, florals and place cards to match your theme.

Whether you want romantic and soft, modern and minimal or bold and glamorous, every table is set by hand to perfection.', '/images/services/table.jpg', 0, 109),
(11, 3, 'photography', 'Photography', 'Capture every moment', 'Every moment, beautifully captured.', 'Your event lasts one day — the photographs last a lifetime. Our photographers work quietly in the background, capturing the natural moments, the details and the emotion, plus the portraits and group shots you will want to frame.

You receive a professionally edited gallery, ready to share, print and treasure.', '/images/services/photography.jpg', 1, 4),
(12, 3, 'videography', 'Videography', 'Cinematic event films', 'Cinematic films of your celebration.', 'Relive every speech, every dance and every smile. Our videographers film your event with cinema-grade cameras, gimbals and drones, then craft a film that tells the story of your day.

Choose a short highlight film for social media, a full-length documentary edit, or both.', '/images/services/videography.jpg', 1, 5),
(13, 3, 'dj-and-entertainment', 'DJ & Entertainment', 'Music and entertainment for every vibe', 'Music and energy for every vibe.', 'The right music keeps the dance floor full all night. Our DJs read the room and mix the perfect soundtrack — from elegant dinner playlists to peak-time party anthems — tailored to your requests.

Add live musicians, singers, dancers or performers to create moments your guests will never forget.', '/images/services/dj.jpg', 1, 6),
(14, 3, 'live-music', 'Live Music', 'Bands, singers and soloists', 'Bands, singers and soloists.', 'Nothing lifts the atmosphere like live music. We work with talented bands, singers, saxophonists, string quartets and pianists to create the soundtrack of your event — from the ceremony and drinks reception to a packed dance floor.

We help you choose the right artists, plan the set list and handle all the technical requirements.', '/images/services/live-music.jpg', 0, 113),
(15, 3, 'entertainment', 'Entertainment', 'Performers that wow your guests', 'Performers that wow your guests.', 'Give your guests moments they will talk about for years. From fire performers and dancers to magicians, acrobats, hosts and themed characters, we book entertainment that fits your event and your audience.

We coordinate timings, space and technical needs so every performance lands perfectly.', '/images/services/entertainment.jpg', 0, 114),
(16, 4, 'sound', 'Sound', 'Professional audio for any space', 'Professional audio for any space.', 'Clear sound is essential — for vows, speeches, presentations and music. Our audio team designs a sound system for your venue and guest numbers, so every word is heard and every song sounds great.

Experienced sound engineers run the system throughout the event, from the first sound check to the final track.', '/images/services/sound.jpg', 0, 115),
(17, 4, 'lighting', 'Lighting', 'Lighting design that transforms a room', 'Lighting design that transforms a room.', 'Lighting changes everything. Warm uplighting makes a room feel intimate, while moving heads and beams turn the dance floor into a show. Our lighting designers create the right mood for every moment of your event.

We plan, install and operate the full lighting rig, including programmed scenes for the entrance, first dance and party.', '/images/services/sound-lighting.jpg', 0, 116),
(18, 4, 'sound-and-lighting', 'Sound & Lighting', 'Professional audio and lighting production', 'Professional audio and lighting production.', 'Crystal-clear sound and beautiful lighting transform any space. Our technical team designs and runs the full audio and lighting setup for your event — from speeches and live music to atmospheric uplighting and dynamic show lighting.

We survey the venue in advance, bring professional equipment and stay on site to run everything on the night.', '/images/services/sound-lighting.jpg', 1, 7),
(19, 4, 'led-screens', 'LED Screens', 'Stunning visuals for bigger impact', 'Stunning visuals for bigger impact.', 'LED screens make your content impossible to miss. Whether it is a keynote presentation, a live camera feed, a brand reveal or a custom visual backdrop for the dance floor, we supply and operate high-resolution screens in any size.

Our team handles content playback, live switching and timing, so every visual appears exactly when it should.', '/images/services/led-screens.jpg', 1, 8),
(20, 4, 'stages', 'Stages', 'Decorated stages & backdrops', 'Beautifully decorated stages, designed around you.', 'The stage is the heart of the room — where the couple sits, the cake is cut and every photo is taken. We design and build decorated stages with floral backdrops, arches, draping, lighting and luxury seating, styled to match your theme.

From a romantic sweetheart stage for a wedding to an elegant backdrop for an engagement or a branded stage for a corporate event, everything is built and dressed by our décor team.', '/images/services/stage-decor.jpg', 1, 9),
(21, 4, 'special-effects', 'Special Effects', 'Create unforgettable moments', 'Create unforgettable moments.', 'Some moments deserve a little magic. Cold spark fountains for the first dance, confetti blasts at midnight, low fog for a dreamy entrance or CO2 jets for a product reveal — our special effects are designed to make your guests gasp.

All effects are indoor-safe where required and operated by trained technicians.', '/images/services/special-effects.jpg', 1, 10),
(22, 4, 'technical-production', 'Technical Production', 'End-to-end technical delivery', 'End-to-end technical delivery.', 'Large events need a technical team that brings everything together. We manage the full production — sound, lighting, LED screens, staging, power and rigging — as one coordinated project with a single point of contact.

From technical drawings and site surveys to show calling on the day, our production managers make sure everything runs safely and on cue.', '/images/services/led-screens-3.jpg', 0, 121);

INSERT INTO service_features (service_id, feature, sort_order) VALUES
(1, 'Initial consultation & creative brief', 1),
(1, 'Budget planning & tracking', 2),
(1, 'Venue sourcing & site visits', 3),
(1, 'Supplier booking & contracts', 4),
(1, 'Timeline, run-sheet & seating plan', 5),
(1, 'On-the-day coordination team', 6),
(2, 'Final-month supplier confirmations', 1),
(2, 'Detailed run-sheet & timeline', 2),
(2, 'Venue walk-through & rehearsal', 3),
(2, 'On-the-day coordination team', 4),
(2, 'Supplier & guest management', 5),
(2, 'Setup and take-down supervision', 6),
(3, 'Creative consultation', 1),
(3, 'Theme & colour palette', 2),
(3, 'Mood boards & material samples', 3),
(3, 'Floor plans & layout design', 4),
(3, '3D visuals on request', 5),
(3, 'Hand-over to the production team', 6),
(4, 'Personal venue shortlist', 1),
(4, 'Availability & price checks', 2),
(4, 'Accompanied site visits', 3),
(4, 'Contract negotiation', 4),
(4, 'Capacity & technical checks', 5),
(4, 'Exclusive partner venues', 6),
(5, 'Furniture & lounge areas', 1),
(5, 'Linens, tableware & glassware', 2),
(5, 'Welcome signage & stationery', 3),
(5, 'Photo corners & backdrops', 4),
(5, 'Candles & décor accents', 5),
(5, 'On-site stylists', 6),
(6, 'Menu design & tasting', 1),
(6, 'Plated, buffet or family-style service', 2),
(6, 'Canapés & food stations', 3),
(6, 'Dietary & allergen options', 4),
(6, 'Bar & drinks packages', 5),
(6, 'Professional waiting staff', 6),
(7, 'Concept & mood boards', 1),
(7, 'Floral arches & installations', 2),
(7, 'Stage & photo backdrops', 3),
(7, 'Table styling & centrepieces', 4),
(7, 'Candles & ambient lighting', 5),
(7, 'Full setup & take-down', 6),
(8, 'Bridal bouquets & buttonholes', 1),
(8, 'Table centrepieces', 2),
(8, 'Floral arches & backdrops', 3),
(8, 'Hanging & ceiling installations', 4),
(8, 'Seasonal & imported blooms', 5),
(8, 'On-site installation', 6),
(9, 'Custom wedding & celebration cakes', 1),
(9, 'Tasting session', 2),
(9, 'Styled dessert tables', 3),
(9, 'Macarons, cupcakes & mini desserts', 4),
(9, 'Dietary options (vegan, gluten-free)', 5),
(9, 'Delivery & setup', 6),
(10, 'Linens & napkin styling', 1),
(10, 'Chargers, cutlery & glassware', 2),
(10, 'Centrepieces & candles', 3),
(10, 'Place cards & menus', 4),
(10, 'Head & sweetheart tables', 5),
(10, 'Full table setup on site', 6),
(11, 'Experienced event photographers', 1),
(11, 'Candid & documentary coverage', 2),
(11, 'Portraits & group photos', 3),
(11, 'Detail & décor shots', 4),
(11, 'Professionally edited gallery', 5),
(11, 'Prints & albums on request', 6),
(12, 'Cinema-grade cameras & gimbals', 1),
(12, 'Drone footage (where permitted)', 2),
(12, 'Highlight film', 3),
(12, 'Full-length edit', 4),
(12, 'Social media reels', 5),
(12, 'Live streaming on request', 6),
(13, 'Professional DJs', 1),
(13, 'Custom playlists & must-play lists', 2),
(13, 'Live bands, singers & musicians', 3),
(13, 'Dancers & performers', 4),
(13, 'MC & host services', 5),
(13, 'Dance floor lighting', 6),
(14, 'Wedding & party bands', 1),
(14, 'Solo singers & acoustic acts', 2),
(14, 'Saxophone & DJ + sax sets', 3),
(14, 'String quartets & pianists', 4),
(14, 'Ceremony & reception music', 5),
(14, 'Sound setup for performers', 6),
(15, 'Dancers & choreographed shows', 1),
(15, 'Fire & LED performers', 2),
(15, 'Magicians & roaming acts', 3),
(15, 'Acrobats & aerial shows', 4),
(15, 'Hosts & MCs', 5),
(15, 'Themed & kids entertainment', 6),
(16, 'PA systems for any size', 1),
(16, 'Wireless & lapel microphones', 2),
(16, 'Mixing desks & monitors', 3),
(16, 'Sound check & rehearsal', 4),
(16, 'Live sound engineers', 5),
(16, 'Ceremony & outdoor audio', 6),
(17, 'Uplighting & wall washing', 1),
(17, 'Fairy lights & festoon', 2),
(17, 'Moving heads & beams', 3),
(17, 'Pin spots for tables & cake', 4),
(17, 'Programmed lighting scenes', 5),
(17, 'Lighting operators on site', 6),
(18, 'PA systems & microphones', 1),
(18, 'Uplighting & ambient lighting', 2),
(18, 'Moving heads & show lighting', 3),
(18, 'Lighting design & programming', 4),
(18, 'Venue technical survey', 5),
(18, 'On-site technicians', 6),
(19, 'Indoor & outdoor LED walls', 1),
(19, 'Custom sizes & shapes', 2),
(19, 'Live camera feeds', 3),
(19, 'Presentation & video playback', 4),
(19, 'Custom visual content', 5),
(19, 'Screen operators on site', 6),
(20, 'Wedding & engagement stages', 1),
(20, 'Floral backdrops & arches', 2),
(20, 'Draping & panel walls', 3),
(20, 'Luxury sofas & seating', 4),
(20, 'Stage lighting & candles', 5),
(20, 'Setup & take-down', 6),
(21, 'Cold spark fountains', 1),
(21, 'Confetti & streamer cannons', 2),
(21, 'Low fog & dry ice', 3),
(21, 'CO2 jets', 4),
(21, 'Bubble & snow machines', 5),
(21, 'Trained effects operators', 6),
(22, 'Production management', 1),
(22, 'Technical site surveys & drawings', 2),
(22, 'Power & rigging', 3),
(22, 'Show calling & cueing', 4),
(22, 'Crew & health and safety', 5),
(22, 'Full AV integration', 6);

INSERT INTO service_images (service_id, image_path, alt_text, sort_order) VALUES
(1, '/images/services/event-planning.jpg', 'Full Event Planning 1', 1),
(1, '/images/services/event-planning-2.jpg', 'Full Event Planning 2', 2),
(1, '/images/services/event-planning-3.jpg', 'Full Event Planning 3', 3),
(1, '/images/services/event-planning-4.jpg', 'Full Event Planning 4', 4),
(2, '/images/about-team.jpg', 'Event Coordination 1', 1),
(2, '/images/services/videography-3.jpg', 'Event Coordination 2', 2),
(2, '/images/cover-trendevent.jpg', 'Event Coordination 3', 3),
(2, '/images/decor-event.avif', 'Event Coordination 4', 4),
(3, '/images/services/concept.jpg', 'Event Concept & Design 1', 1),
(3, '/images/services/concept-2.jpg', 'Event Concept & Design 2', 2),
(3, '/images/services/concept-3.jpg', 'Event Concept & Design 3', 3),
(3, '/images/services/event-planning.jpg', 'Event Concept & Design 4', 4),
(4, 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1600&q=75', 'Venue Finding 1', 1),
(4, 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1600&q=75', 'Venue Finding 2', 2),
(4, 'https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=1600&q=75', 'Venue Finding 3', 3),
(4, 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1600&q=75', 'Venue Finding 4', 4),
(5, '/images/services/styling.jpg', 'Event Styling 1', 1),
(5, '/images/services/styling-2.jpg', 'Event Styling 2', 2),
(5, '/images/services/styling-3.jpg', 'Event Styling 3', 3),
(5, '/images/private-parties.avif', 'Event Styling 4', 4),
(6, '/images/services/catering.jpg', 'Catering 1', 1),
(6, '/images/services/catering-2.jpg', 'Catering 2', 2),
(6, '/images/services/catering-3.jpg', 'Catering 3', 3),
(6, '/images/services/catering-4.jpg', 'Catering 4', 4),
(7, '/images/event-engagement.jpg', 'Decoration 1', 1),
(7, '/images/cover-trendevent.jpg', 'Decoration 2', 2),
(7, '/images/event-wedding.jpg', 'Decoration 3', 3),
(7, '/images/decor-event.avif', 'Decoration 4', 4),
(8, '/images/services/flowers.jpg', 'Flowers 1', 1),
(8, '/images/services/flowers-2.jpg', 'Flowers 2', 2),
(8, '/images/hero.jpg', 'Flowers 3', 3),
(8, '/images/event-wedding.jpg', 'Flowers 4', 4),
(9, '/images/services/cakes.jpg', 'Cakes & Desserts 1', 1),
(9, '/images/services/cakes-2.jpg', 'Cakes & Desserts 2', 2),
(9, '/images/services/cakes-3.jpg', 'Cakes & Desserts 3', 3),
(9, '/images/services/cakes-4.jpg', 'Cakes & Desserts 4', 4),
(10, '/images/services/table.jpg', 'Table Styling 1', 1),
(10, '/images/services/table-2.jpg', 'Table Styling 2', 2),
(10, '/images/services/table-3.jpg', 'Table Styling 3', 3),
(10, '/images/services/table-4.jpg', 'Table Styling 4', 4),
(11, '/images/services/photography.jpg', 'Photography 1', 1),
(11, '/images/services/photography-2.jpg', 'Photography 2', 2),
(11, '/images/services/photography-3.jpg', 'Photography 3', 3),
(11, '/images/services/photography-4.jpg', 'Photography 4', 4),
(12, '/images/services/videography.jpg', 'Videography 1', 1),
(12, '/images/services/videography-2.jpg', 'Videography 2', 2),
(12, '/images/services/videography-3.jpg', 'Videography 3', 3),
(12, '/images/services/videography-4.jpg', 'Videography 4', 4),
(13, '/images/services/dj.jpg', 'DJ & Entertainment 1', 1),
(13, '/images/services/dj-2.jpg', 'DJ & Entertainment 2', 2),
(13, '/images/services/dj-3.jpg', 'DJ & Entertainment 3', 3),
(13, '/images/services/dj-4.jpg', 'DJ & Entertainment 4', 4),
(14, '/images/services/live-music.jpg', 'Live Music 1', 1),
(14, '/images/services/live-music-2.jpg', 'Live Music 2', 2),
(14, '/images/services/live-music-3.jpg', 'Live Music 3', 3),
(14, '/images/services/live-music-4.jpg', 'Live Music 4', 4),
(15, '/images/services/entertainment.jpg', 'Entertainment 1', 1),
(15, '/images/services/entertainment-2.jpg', 'Entertainment 2', 2),
(15, '/images/services/stages-3.jpg', 'Entertainment 3', 3),
(15, '/images/services/special-effects-3.jpg', 'Entertainment 4', 4),
(16, '/images/services/sound.jpg', 'Sound 1', 1),
(16, '/images/services/sound-2.jpg', 'Sound 2', 2),
(16, '/images/services/sound-3.jpg', 'Sound 3', 3),
(16, '/images/services/sound-lighting-3.jpg', 'Sound 4', 4),
(17, '/images/services/sound-lighting.jpg', 'Lighting 1', 1),
(17, '/images/services/sound-lighting-2.jpg', 'Lighting 2', 2),
(17, '/images/services/stages.jpg', 'Lighting 3', 3),
(17, '/images/services/sound-lighting-4.jpg', 'Lighting 4', 4),
(18, '/images/services/sound-lighting.jpg', 'Sound & Lighting 1', 1),
(18, '/images/services/sound-lighting-2.jpg', 'Sound & Lighting 2', 2),
(18, '/images/services/sound-lighting-3.jpg', 'Sound & Lighting 3', 3),
(18, '/images/services/sound-lighting-4.jpg', 'Sound & Lighting 4', 4),
(19, '/images/services/led-screens.jpg', 'LED Screens 1', 1),
(19, '/images/services/led-screens-2.jpg', 'LED Screens 2', 2),
(19, '/images/services/led-screens-3.jpg', 'LED Screens 3', 3),
(19, '/images/services/led-screens-4.jpg', 'LED Screens 4', 4),
(20, '/images/services/stage-decor.jpg', 'Stages 1', 1),
(20, '/images/services/stage-decor-2.jpg', 'Stages 2', 2),
(20, '/images/services/stage-decor-3.jpg', 'Stages 3', 3),
(20, '/images/services/stage-decor-4.jpg', 'Stages 4', 4),
(21, '/images/services/special-effects.jpg', 'Special Effects 1', 1),
(21, '/images/services/special-effects-2.jpg', 'Special Effects 2', 2),
(21, '/images/services/special-effects-3.jpg', 'Special Effects 3', 3),
(21, '/images/services/special-effects-4.jpg', 'Special Effects 4', 4),
(22, '/images/services/led-screens-3.jpg', 'Technical Production 1', 1),
(22, '/images/services/stages-2.jpg', 'Technical Production 2', 2),
(22, '/images/services/stages-4.jpg', 'Technical Production 3', 3),
(22, '/images/services/led-screens.jpg', 'Technical Production 4', 4);

-- 6. VENUE CATEGORIES
CREATE TABLE venue_categories (
  id         INT UNSIGNED NOT NULL AUTO_INCREMENT,
  slug       VARCHAR(120) NOT NULL,
  name       VARCHAR(150) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uq_venue_categories_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO venue_categories (id, slug, name, sort_order) VALUES
(1, 'wedding-venues', 'Wedding Venues', 1),
(2, 'birthday-venues', 'Birthday Venues', 2),
(3, 'party-venues', 'Party Venues', 3),
(4, 'corporate-venues', 'Corporate Venues', 4),
(5, 'conference-venues', 'Conference Venues', 5),
(6, 'luxury-venues', 'Luxury Venues', 6),
(7, 'outdoor-venues', 'Outdoor Venues', 7),
(8, 'hotels', 'Hotels', 8),
(9, 'banqueting-halls', 'Banqueting Halls', 9),
(10, 'restaurants', 'Restaurants', 10),
(11, 'rooftops', 'Rooftops', 11),
(12, 'unique-venues', 'Unique Venues', 12);

-- 7. VENUES — slug = URL /venues/<slug>
CREATE TABLE venues (
  id          INT UNSIGNED NOT NULL AUTO_INCREMENT,
  slug        VARCHAR(120) NOT NULL,
  name        VARCHAR(150) NOT NULL,
  city_id     INT UNSIGNED NOT NULL,
  capacity    INT NOT NULL,
  price_from  DECIMAL(10,2) NOT NULL,
  currency    CHAR(3) NOT NULL DEFAULT 'GBP',
  description TEXT NULL,
  address     VARCHAR(255) NULL,
  is_featured TINYINT(1) NOT NULL DEFAULT 1,
  sort_order  INT NOT NULL DEFAULT 0,
  is_active   TINYINT(1) NOT NULL DEFAULT 1,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_venues_slug (slug),
  KEY idx_venues_city (city_id),
  KEY idx_venues_capacity (capacity),
  CONSTRAINT fk_venues_city FOREIGN KEY (city_id) REFERENCES cities (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE venue_category_map (
  venue_id    INT UNSIGNED NOT NULL,
  category_id INT UNSIGNED NOT NULL,
  PRIMARY KEY (venue_id, category_id),
  KEY idx_vcm_category (category_id),
  CONSTRAINT fk_vcm_venue FOREIGN KEY (venue_id) REFERENCES venues (id) ON DELETE CASCADE,
  CONSTRAINT fk_vcm_category FOREIGN KEY (category_id) REFERENCES venue_categories (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE venue_images (
  id         INT UNSIGNED NOT NULL AUTO_INCREMENT,
  venue_id   INT UNSIGNED NOT NULL,
  image_path VARCHAR(255) NOT NULL,
  alt_text   VARCHAR(255) NULL,
  is_cover   TINYINT(1) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_vi_venue (venue_id, sort_order),
  CONSTRAINT fk_vi_venue FOREIGN KEY (venue_id) REFERENCES venues (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO venues (id, slug, name, city_id, capacity, price_from, currency, description, is_featured, sort_order) VALUES
(1, 'the-grand-hall', 'The Grand Hall', 1, 350, 2500, 'GBP', 'A timeless ballroom with crystal chandeliers, soaring ceilings and a sprung dance floor — made for grand weddings and gala dinners.', 1, 1),
(2, 'riverside-terrace', 'Riverside Terrace', 1, 200, 2000, 'GBP', 'An open-air terrace on the water with sunset views over the city skyline — perfect for summer receptions and cocktail parties.', 1, 2),
(3, 'the-crystal-room', 'The Crystal Room', 2, 400, 3000, 'GBP', 'Golden light, mirrored walls and a statement chandelier. The Crystal Room turns every celebration into an occasion.', 1, 3),
(4, 'skyline-view', 'Skyline View', 3, 250, 2200, 'GBP', 'A glass-walled rooftop space high above the city, ideal for launches, corporate evenings and after-dark parties.', 1, 4),
(5, 'the-garden-estate', 'The Garden Estate', 4, 300, 2800, 'GBP', 'Manicured lawns, rose gardens and a floral aisle — a romantic countryside setting just outside the city.', 1, 5),
(6, 'the-summit-centre', 'The Summit Centre', 1, 600, 3500, 'GBP', 'A flexible conference venue with built-in AV, breakout rooms and a 600-seat auditorium.', 1, 6),
(7, 'the-loft-kitchen', 'The Loft Kitchen', 5, 90, 1200, 'GBP', 'An industrial-chic restaurant with a private dining room — great for birthday dinners and intimate parties.', 1, 7),
(8, 'azure-bay-resort', 'Azure Bay Resort', 5, 220, 3200, 'GBP', 'A luxury resort hotel with poolside terraces and elegant suites for destination-style weddings and retreats.', 1, 8);

INSERT INTO venue_category_map (venue_id, category_id) VALUES
(1, 1),
(1, 9),
(1, 6),
(1, 4),
(1, 3),
(2, 7),
(2, 3),
(2, 2),
(2, 1),
(2, 11),
(3, 1),
(3, 6),
(3, 9),
(3, 8),
(4, 11),
(4, 4),
(4, 3),
(4, 12),
(4, 2),
(5, 1),
(5, 7),
(5, 12),
(5, 6),
(6, 5),
(6, 4),
(6, 8),
(7, 10),
(7, 2),
(7, 3),
(7, 12),
(8, 8),
(8, 6),
(8, 1),
(8, 7);

INSERT INTO venue_images (venue_id, image_path, alt_text, is_cover, sort_order) VALUES
(1, 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1600&q=75', 'The Grand Hall 1', 1, 1),
(1, 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1600&q=75', 'The Grand Hall 2', 0, 2),
(1, 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=1600&q=75', 'The Grand Hall 3', 0, 3),
(2, 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1600&q=75', 'Riverside Terrace 1', 1, 1),
(2, 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1600&q=75', 'Riverside Terrace 2', 0, 2),
(2, 'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&w=1600&q=75', 'Riverside Terrace 3', 0, 3),
(3, 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1600&q=75', 'The Crystal Room 1', 1, 1),
(3, '/images/event-wedding.jpg', 'The Crystal Room 2', 0, 2),
(3, 'https://images.unsplash.com/photo-1522413452208-996ff3f3e740?auto=format&fit=crop&w=1600&q=75', 'The Crystal Room 3', 0, 3),
(4, 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=1600&q=75', 'Skyline View 1', 1, 1),
(4, 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?auto=format&fit=crop&w=1600&q=75', 'Skyline View 2', 0, 2),
(4, 'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=1600&q=75', 'Skyline View 3', 0, 3),
(5, 'https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=1600&q=75', 'The Garden Estate 1', 1, 1),
(5, 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=1600&q=75', 'The Garden Estate 2', 0, 2),
(5, 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?auto=format&fit=crop&w=1600&q=75', 'The Garden Estate 3', 0, 3),
(6, 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1600&q=75', 'The Summit Centre 1', 1, 1),
(6, 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1600&q=75', 'The Summit Centre 2', 0, 2),
(6, 'https://images.unsplash.com/photo-1560439513-74b037a25d84?auto=format&fit=crop&w=1600&q=75', 'The Summit Centre 3', 0, 3),
(7, 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1600&q=75', 'The Loft Kitchen 1', 1, 1),
(7, 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1600&q=75', 'The Loft Kitchen 2', 0, 2),
(7, 'https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=1600&q=75', 'The Loft Kitchen 3', 0, 3),
(8, 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1600&q=75', 'Azure Bay Resort 1', 1, 1),
(8, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1600&q=75', 'Azure Bay Resort 2', 0, 2),
(8, 'https://images.unsplash.com/photo-1544078751-58fee2d8a03b?auto=format&fit=crop&w=1600&q=75', 'Azure Bay Resort 3', 0, 3);

-- 8. PACKAGES — price_from NULL = tailored price (Custom Package → Build Your Event)
CREATE TABLE packages (
  id          INT UNSIGNED NOT NULL AUTO_INCREMENT,
  slug        VARCHAR(120) NOT NULL,
  name        VARCHAR(150) NOT NULL,
  description VARCHAR(500) NULL,
  price_from  DECIMAL(10,2) NULL,
  currency    CHAR(3) NOT NULL DEFAULT 'GBP',
  image       VARCHAR(255) NULL,
  is_popular  TINYINT(1) NOT NULL DEFAULT 0,
  sort_order  INT NOT NULL DEFAULT 0,
  is_active   TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uq_packages_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE package_items (
  id         INT UNSIGNED NOT NULL AUTO_INCREMENT,
  package_id INT UNSIGNED NOT NULL,
  item       VARCHAR(255) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_pi_package (package_id, sort_order),
  CONSTRAINT fk_pi_package FOREIGN KEY (package_id) REFERENCES packages (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO packages (id, slug, name, description, price_from, currency, image, is_popular, sort_order) VALUES
(1, 'wedding-packages', 'Wedding Packages', 'Everything for your big day, from venue to the final dance.', 8500, 'GBP', '/images/event-wedding.jpg', 0, 1),
(2, 'birthday-packages', 'Birthday Packages', 'Milestone birthdays with styling, cake and entertainment.', 1500, 'GBP', '/images/event-birthday.jpg', 0, 2),
(3, 'corporate-packages', 'Corporate Packages', 'Professional events delivered on time and on brand.', 4000, 'GBP', 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1600&q=75', 0, 3),
(4, 'venue-catering', 'Venue + Catering', 'The perfect space paired with an exquisite menu.', 3000, 'GBP', 'https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&w=1600&q=75', 0, 4),
(5, 'venue-d-cor', 'Venue + Décor', 'A beautiful room, styled from floor to ceiling.', 3200, 'GBP', 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1600&q=75', 0, 5),
(6, 'full-event-package', 'Full Event Package', 'One team handles everything — you simply arrive and celebrate.', 12000, 'GBP', '/images/cover-trendevent.jpg', 1, 6),
(7, 'custom-package', 'Custom Package', 'Pick exactly the services you need and we will tailor a proposal.', NULL, 'GBP', 'https://images.unsplash.com/photo-1522413452208-996ff3f3e740?auto=format&fit=crop&w=1600&q=75', 0, 7);

INSERT INTO package_items (package_id, item, sort_order) VALUES
(1, 'Venue sourcing', 1),
(1, 'Full planning & coordination', 2),
(1, 'Floral & décor styling', 3),
(1, 'Catering', 4),
(1, 'Photography', 5),
(2, 'Venue', 1),
(2, 'Themed decoration', 2),
(2, 'Cake & desserts', 3),
(2, 'DJ', 4),
(3, 'Venue', 1),
(3, 'Event coordination', 2),
(3, 'Catering', 3),
(3, 'Sound, lighting & LED screens', 4),
(4, 'Venue hire', 1),
(4, 'Menu tasting', 2),
(4, 'Catering & service staff', 3),
(5, 'Venue hire', 1),
(5, 'Concept & styling', 2),
(5, 'Flowers', 3),
(5, 'Table styling', 4),
(6, 'Venue', 1),
(6, 'Full planning', 2),
(6, 'Catering & décor', 3),
(6, 'Photo & video', 4),
(6, 'Entertainment', 5),
(6, 'Technical production', 6),
(7, 'Choose any venue', 1),
(7, 'Choose any services', 2),
(7, 'Tailored proposal', 3),
(7, 'Tailored price', 4);

-- 9. PORTFOLIO (Our Work)
CREATE TABLE portfolio_items (
  id            INT UNSIGNED NOT NULL AUTO_INCREMENT,
  slug          VARCHAR(150) NOT NULL,
  title         VARCHAR(200) NOT NULL,
  event_type_id INT UNSIGNED NOT NULL,
  description   TEXT NULL,
  cover_image   VARCHAR(255) NULL,
  event_date    DATE NULL,
  sort_order    INT NOT NULL DEFAULT 0,
  is_active     TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uq_portfolio_slug (slug),
  KEY idx_portfolio_event_type (event_type_id),
  CONSTRAINT fk_portfolio_event_type FOREIGN KEY (event_type_id) REFERENCES event_types (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE portfolio_images (
  id           INT UNSIGNED NOT NULL AUTO_INCREMENT,
  portfolio_id INT UNSIGNED NOT NULL,
  image_path   VARCHAR(255) NOT NULL,
  alt_text     VARCHAR(255) NULL,
  sort_order   INT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_pimg_portfolio (portfolio_id, sort_order),
  CONSTRAINT fk_pimg_portfolio FOREIGN KEY (portfolio_id) REFERENCES portfolio_items (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO portfolio_items (id, slug, title, event_type_id, cover_image, sort_order) VALUES
(1, 'a-white-rose-reception', 'A White Rose Reception', 1, '/images/event-wedding.jpg', 1),
(2, 'candlelight-by-the-river', 'Candlelight by the River', 1, '/images/cover-trendevent.jpg', 2),
(3, 'tech-summit-2026', 'Tech Summit 2026', 7, '/images/conference.avif', 3),
(4, 'sunset-floral-birthday', 'Sunset Floral Birthday', 2, '/images/event-birthday.jpg', 4),
(5, 'the-grand-reveal', 'The Grand Reveal', 8, '/images/event-product-launch.jpg', 5),
(6, 'a-champagne-engagement', 'A Champagne Engagement', 3, '/images/engagment-1.avif', 6),
(7, 'red-carpet-awards-gala', 'Red Carpet Awards Gala', 9, '/images/event-award-night.jpg', 7),
(8, 'poolside-summer-party', 'Poolside Summer Party', 5, '/images/private-parties.avif', 8),
(9, 'festive-team-celebration', 'Festive Team Celebration', 10, '/images/event-christmas-party.jpg', 9),
(10, 'orchids-and-champagne-reception', 'Orchids & Champagne Reception', 1, '/images/decor-event.avif', 10),
(11, 'garden-brand-soir-e', 'Garden Brand Soirée', 11, '/images/event-brand-event.jpg', 11),
(12, 'sunset-baby-shower', 'Sunset Baby Shower', 4, '/images/event-baby-shower.jpg', 12);

INSERT INTO portfolio_images (portfolio_id, image_path, alt_text, sort_order) VALUES
(1, '/images/event-wedding.jpg', 'A White Rose Reception', 1),
(2, '/images/cover-trendevent.jpg', 'Candlelight by the River', 1),
(3, '/images/conference.avif', 'Tech Summit 2026', 1),
(4, '/images/event-birthday.jpg', 'Sunset Floral Birthday', 1),
(5, '/images/event-product-launch.jpg', 'The Grand Reveal', 1),
(6, '/images/engagment-1.avif', 'A Champagne Engagement', 1),
(7, '/images/event-award-night.jpg', 'Red Carpet Awards Gala', 1),
(8, '/images/private-parties.avif', 'Poolside Summer Party', 1),
(9, '/images/event-christmas-party.jpg', 'Festive Team Celebration', 1),
(10, '/images/decor-event.avif', 'Orchids & Champagne Reception', 1),
(11, '/images/event-brand-event.jpg', 'Garden Brand Soirée', 1),
(12, '/images/event-baby-shower.jpg', 'Sunset Baby Shower', 1);

-- 10. USERS (Account page) — passwords stored with PHP password_hash()
CREATE TABLE users (
  id            INT UNSIGNED NOT NULL AUTO_INCREMENT,
  full_name     VARCHAR(150) NOT NULL,
  email         VARCHAR(190) NOT NULL,
  phone         VARCHAR(30) NULL,
  password_hash VARCHAR(255) NOT NULL,
  role          ENUM('customer','admin') NOT NULL DEFAULT 'customer',
  is_active     TINYINT(1) NOT NULL DEFAULT 1,
  created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Password reset links (token stored as SHA-256 hash, valid 1 hour)
CREATE TABLE password_resets (
  id         INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id    INT UNSIGNED NOT NULL,
  token_hash CHAR(64) NOT NULL,
  expires_at DATETIME NOT NULL,
  used_at    DATETIME NULL,
  ip_address VARCHAR(45) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_pr_token (token_hash),
  KEY idx_pr_user (user_id, created_at),
  CONSTRAINT fk_pr_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 11. SAVED VENUES (♡) — user_id for members, device_token for guests
CREATE TABLE saved_venues (
  id           INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id      INT UNSIGNED NULL,
  device_token VARCHAR(64) NULL,
  venue_id     INT UNSIGNED NOT NULL,
  created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_saved_user_venue (user_id, venue_id),
  UNIQUE KEY uq_saved_device_venue (device_token, venue_id),
  KEY idx_saved_venue (venue_id),
  CONSTRAINT fk_saved_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_saved_venue FOREIGN KEY (venue_id) REFERENCES venues (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 12. QUOTE REQUESTS — Get a Quote, Check Availability, package/service quotes; source = page it came from
CREATE TABLE quote_requests (
  id             INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id        INT UNSIGNED NULL,
  full_name      VARCHAR(150) NOT NULL,
  email          VARCHAR(190) NOT NULL,
  phone          VARCHAR(30) NULL,
  event_type_id  INT UNSIGNED NULL,
  event_date     DATE NULL,
  guest_range_id INT UNSIGNED NULL,
  city_id        INT UNSIGNED NULL,
  venue_id       INT UNSIGNED NULL,
  package_id     INT UNSIGNED NULL,
  service_id     INT UNSIGNED NULL,
  message        TEXT NULL,
  source         ENUM('quote_form','venue_page','package_page','service_page','build_page','homepage_search') NOT NULL DEFAULT 'quote_form',
  `status`       ENUM('new','contacted','quoted','won','lost') NOT NULL DEFAULT 'new',
  admin_notes    TEXT NULL,
  ip_address     VARCHAR(45) NULL,
  created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_qr_status (`status`, created_at),
  KEY idx_qr_email (email),
  CONSTRAINT fk_qr_user       FOREIGN KEY (user_id)        REFERENCES users (id)        ON DELETE SET NULL,
  CONSTRAINT fk_qr_event_type FOREIGN KEY (event_type_id)  REFERENCES event_types (id)  ON DELETE SET NULL,
  CONSTRAINT fk_qr_guests     FOREIGN KEY (guest_range_id) REFERENCES guest_ranges (id) ON DELETE SET NULL,
  CONSTRAINT fk_qr_city       FOREIGN KEY (city_id)        REFERENCES cities (id)       ON DELETE SET NULL,
  CONSTRAINT fk_qr_venue      FOREIGN KEY (venue_id)       REFERENCES venues (id)       ON DELETE SET NULL,
  CONSTRAINT fk_qr_package    FOREIGN KEY (package_id)     REFERENCES packages (id)     ON DELETE SET NULL,
  CONSTRAINT fk_qr_service    FOREIGN KEY (service_id)     REFERENCES services (id)     ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 13. EVENT BUILDS (Build Your Event) — city NULL = Any, venue NULL = To be suggested
CREATE TABLE event_builds (
  id               INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id          INT UNSIGNED NULL,
  quote_request_id INT UNSIGNED NULL,
  event_type_id    INT UNSIGNED NULL,
  city_id          INT UNSIGNED NULL,
  event_date       DATE NULL,
  guest_range_id   INT UNSIGNED NULL,
  venue_id         INT UNSIGNED NULL,
  `status`         ENUM('draft','submitted','proposal_sent','confirmed','cancelled') NOT NULL DEFAULT 'draft',
  created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_eb_status (`status`),
  CONSTRAINT fk_eb_user   FOREIGN KEY (user_id)          REFERENCES users (id)          ON DELETE SET NULL,
  CONSTRAINT fk_eb_quote  FOREIGN KEY (quote_request_id) REFERENCES quote_requests (id) ON DELETE SET NULL,
  CONSTRAINT fk_eb_type   FOREIGN KEY (event_type_id)    REFERENCES event_types (id)    ON DELETE SET NULL,
  CONSTRAINT fk_eb_city   FOREIGN KEY (city_id)          REFERENCES cities (id)         ON DELETE SET NULL,
  CONSTRAINT fk_eb_guests FOREIGN KEY (guest_range_id)   REFERENCES guest_ranges (id)   ON DELETE SET NULL,
  CONSTRAINT fk_eb_venue  FOREIGN KEY (venue_id)         REFERENCES venues (id)         ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE event_build_services (
  event_build_id INT UNSIGNED NOT NULL,
  service_id     INT UNSIGNED NOT NULL,
  PRIMARY KEY (event_build_id, service_id),
  KEY idx_ebs_service (service_id),
  CONSTRAINT fk_ebs_build   FOREIGN KEY (event_build_id) REFERENCES event_builds (id) ON DELETE CASCADE,
  CONSTRAINT fk_ebs_service FOREIGN KEY (service_id)     REFERENCES services (id)     ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 14. SITE SETTINGS (contacts, footer, About stats)
CREATE TABLE site_settings (
  setting_key   VARCHAR(100) NOT NULL,
  setting_value TEXT NULL,
  PRIMARY KEY (setting_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO site_settings (setting_key, setting_value) VALUES
('site_name', 'Trend Events'),
('tagline', 'We Create. You Celebrate.'),
('hero_subtitle', 'From the perfect venue to the final light.'),
('phone', '+44 7308 214398'),
('email', 'Trendeventsuk@gmail.com'),
('instagram', '@trendevents.uk'),
('instagram_url', 'https://www.instagram.com/trendevents.uk/'),
('address', 'London, United Kingdom'),
('working_hours', 'Mon–Sat, 9:00–19:00'),
('stats_events', '500+'),
('stats_partner_venues', '120+'),
('stats_specialists', '40+'),
('stats_rating', '4.9'),
('footer_text', 'We create. You celebrate. From the perfect venue to the final light.');

SET FOREIGN_KEY_CHECKS = 1;
